<a href="https://colab.research.google.com/github/dhirajnh11/EY-MarApr26/blob/main/02_10_minutes_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Introduction

When working with tabular data, such as data stored in spreadsheets or databases, pandas is the right tool for you. pandas will help you to explore, clean, and process your data.
This is a short introduction to pandas, geared mainly for new users.

we import pandas and NumPy as follows.

In [40]:
import numpy as np
import pandas as pd # TABULAR DATA -> pandas manipulates as PANEL DATAFRAME

## Object Creation

`Series` is a one-dimensional labeled array capable of holding data of any type

Creating a `Series` by passing a list of values, leting pandas create a default integer index:

In [41]:
s = pd.Series([1, 2, 4, np.nan, 9, 0])
print(s)

0    1.0
1    2.0
2    4.0
3    NaN
4    9.0
5    0.0
dtype: float64

In pandas, a data table is called a `DataFrame`. Creating a `DataFrame` by passing a NumPy array, with a datetime index and labeled columns:

In [42]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [43]:
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = list('ABCD'))
#df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns = ['1.2','abc','123', ' hello world'])
df

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279
2013-01-06 -0.807586 -1.511296  0.664316 -0.477089

Creating a `DataFrame` by passing a dict of objects that can be conversted to series-like.

In [44]:
df2 = pd.DataFrame({'A': 1.0,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of resulting `DataFrame` have different `dtypes`

In [45]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

As you can see, the columns `A`, `B`, `C` and `D` are automaticallly tab completed. `E` and `F` are there as well the rest of the attriutes have been truncated for brevity.

## Viewing data

Here is how to view the top and bottom rows of the DataFrame.

In [46]:
df.head() # from top to bottom

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279

In [47]:
df.head(2)

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312

In [48]:
df.tail(3) # bottom to top

                   A         B         C         D
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279
2013-01-06 -0.807586 -1.511296  0.664316 -0.477089

Display the index, columns.

In [49]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [50]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

`describe()` to show a quick statistic summary of your data.

In [51]:
print(dir(df)) # open anything as a directory

['A', 'B', 'C', 'D', 'T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']

In [52]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.405666 -0.070062 -0.244742  0.068355
std    0.867239  1.327725  1.177495  1.382507
min   -0.807586 -1.783594 -2.429343 -2.095631
25%    0.038308 -1.113113 -0.477419 -0.460887
50%    0.236653  0.153345  0.142555  0.016923
75%    0.917736  0.936657  0.547508  0.953265
max    1.651316  1.394037  0.677368  1.826690

Transposing your data.

In [53]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.651316    0.332189    0.141116    1.112918    0.004039   -0.807586
B    1.394037   -1.783594    0.081434    0.225255    1.173792   -1.511296
C    0.677368    0.197084   -2.429343   -0.665900    0.088026    0.664316
D   -2.095631    1.122312    1.826690    0.446125   -0.412279   -0.477089

In [54]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.405666 -0.070062 -0.244742  0.068355
std    0.867239  1.327725  1.177495  1.382507
min   -0.807586 -1.783594 -2.429343 -2.095631
25%    0.038308 -1.113113 -0.477419 -0.460887
50%    0.236653  0.153345  0.142555  0.016923
75%    0.917736  0.936657  0.547508  0.953265
max    1.651316  1.394037  0.677368  1.826690

In [55]:
df.describe().T

   count      mean       std       min       25%       50%       75%       max
A    6.0  0.405666  0.867239 -0.807586  0.038308  0.236653  0.917736  1.651316
B    6.0 -0.070062  1.327725 -1.783594 -1.113113  0.153345  0.936657  1.394037
C    6.0 -0.244742  1.177495 -2.429343 -0.477419  0.142555  0.547508  0.677368
D    6.0  0.068355  1.382507 -2.095631 -0.460887  0.016923  0.953265  1.826690

In [56]:
# extract all the average values from all columns

df.describe().T['mean']

A    0.405666
B   -0.070062
C   -0.244742
D    0.068355
Name: mean, dtype: float64

Sotring by an axis

In [57]:
df.sort_index(axis=0, ascending=False) # values inside index sorted

                   A         B         C         D
2013-01-06 -0.807586 -1.511296  0.664316 -0.477089
2013-01-05  0.004039  1.173792  0.088026 -0.412279
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-01  1.651316  1.394037  0.677368 -2.095631

In [58]:
df.sort_index(axis=1, ascending=False) # COLUMNS should be sorted, Not the index time stamps!

                   D         C         B         A
2013-01-01 -2.095631  0.677368  1.394037  1.651316
2013-01-02  1.122312  0.197084 -1.783594  0.332189
2013-01-03  1.826690 -2.429343  0.081434  0.141116
2013-01-04  0.446125 -0.665900  0.225255  1.112918
2013-01-05 -0.412279  0.088026  1.173792  0.004039
2013-01-06 -0.477089  0.664316 -1.511296 -0.807586

Sotring by values

In [59]:
df.sort_values( by='B')

                   A         B         C         D
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-06 -0.807586 -1.511296  0.664316 -0.477089
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279
2013-01-01  1.651316  1.394037  0.677368 -2.095631

## Selection

### Getting

Selecting a single column, which yields a `Series`, equivalent to `df.A`

In [60]:
#df[['A','C']] # SELECTION OF COLUMN is the default value for selection
df['A']

2013-01-01    1.651316
2013-01-02    0.332189
2013-01-03    0.141116
2013-01-04    1.112918
2013-01-05    0.004039
2013-01-06   -0.807586
Freq: D, Name: A, dtype: float64

Selecting via [ ], which slice the rows

In [61]:
df[0:2] # [from, to) [ means include, ) means exclude

# 0, 1 is included, 2 is excluded

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312

In [62]:
df[-3:-1]

                   A         B         C         D
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279

### Selection by label

For getting a cross section using a label

In [63]:
dates[0]

Timestamp('2013-01-01 00:00:00')

In [64]:
df.loc[dates[0]]

A    1.651316
B    1.394037
C    0.677368
D   -2.095631
Name: 2013-01-01 00:00:00, dtype: float64

Selection on a multi-axis by label

In [65]:
df.loc['2013-01-01':'2013-01-03', ['A', 'B']]

                   A         B
2013-01-01  1.651316  1.394037
2013-01-02  0.332189 -1.783594
2013-01-03  0.141116  0.081434

In [66]:
df.loc[:, ['A', 'B']] # : means select * or everything!

# dataframe.loc [ row selection, column selection]

                   A         B
2013-01-01  1.651316  1.394037
2013-01-02  0.332189 -1.783594
2013-01-03  0.141116  0.081434
2013-01-04  1.112918  0.225255
2013-01-05  0.004039  1.173792
2013-01-06 -0.807586 -1.511296

### Selection by position

In [67]:
df.iloc[3]

A    1.112918
B    0.225255
C   -0.665900
D    0.446125
Name: 2013-01-04 00:00:00, dtype: float64

By integer slices, acting similar to numpy/python

In [68]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  1.112918  0.225255
2013-01-05  0.004039  1.173792

For slicing rows explicitly

In [69]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-03  0.141116  0.081434 -2.429343  1.826690

For slicing columns explicitly

In [70]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  1.394037  0.677368
2013-01-02 -1.783594  0.197084
2013-01-03  0.081434 -2.429343
2013-01-04  0.225255 -0.665900
2013-01-05  1.173792  0.088026
2013-01-06 -1.511296  0.664316

### Boolean indexing

using a single column's values to select data

In [71]:
df[df['A'] > 0]

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-04  1.112918  0.225255 -0.665900  0.446125
2013-01-05  0.004039  1.173792  0.088026 -0.412279

In [72]:
df[df['A'] > 0]['B'] # Filter from 1 column and apply changes to another column

# filter was applied on A, and then corresponding B values were printed

2013-01-01    1.394037
2013-01-02   -1.783594
2013-01-03    0.081434
2013-01-04    0.225255
2013-01-05    1.173792
Freq: D, Name: B, dtype: float64

Selecting values from a DataFrame where a boolean condition is met

In [73]:
df[df > 0]

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368       NaN
2013-01-02  0.332189       NaN  0.197084  1.122312
2013-01-03  0.141116  0.081434       NaN  1.826690
2013-01-04  1.112918  0.225255       NaN  0.446125
2013-01-05  0.004039  1.173792  0.088026       NaN
2013-01-06       NaN       NaN  0.664316       NaN

using `isin()` method for filtering

In [74]:
df2 = df.copy() # Creates a DEEP COPY
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']

df2

                   A         B         C         D      E
2013-01-01  1.651316  1.394037  0.677368 -2.095631    one
2013-01-02  0.332189 -1.783594  0.197084  1.122312    one
2013-01-03  0.141116  0.081434 -2.429343  1.826690    two
2013-01-04  1.112918  0.225255 -0.665900  0.446125  three
2013-01-05  0.004039  1.173792  0.088026 -0.412279   four
2013-01-06 -0.807586 -1.511296  0.664316 -0.477089  three

In [75]:
df2[df2['E'].isin(['two', 'four'])]

                   A         B         C         D     E
2013-01-03  0.141116  0.081434 -2.429343  1.826690   two
2013-01-05  0.004039  1.173792  0.088026 -0.412279  four

## Missing data

pandas primarily uses the `np.nan` to represent missing data. It is by default not inclued in a computations.
Reindexing allows you to change/add/delete the index on a special axis. This return a copy of data.

In [76]:
df1 = df.reindex(index = dates[0:4], columns = list(df.columns) + ['E'])
df1.loc[dates[0] : dates[1], 'E'] = 1
df1

                   A         B         C         D    E
2013-01-01  1.651316  1.394037  0.677368 -2.095631  1.0
2013-01-02  0.332189 -1.783594  0.197084  1.122312  1.0
2013-01-03  0.141116  0.081434 -2.429343  1.826690  NaN
2013-01-04  1.112918  0.225255 -0.665900  0.446125  NaN

Top drop any rows that have missing data.

In [77]:
df1.dropna(how='any')

                   A         B         C         D    E
2013-01-01  1.651316  1.394037  0.677368 -2.095631  1.0
2013-01-02  0.332189 -1.783594  0.197084  1.122312  1.0

In [78]:
df1.dropna(axis=1)

                   A         B         C         D
2013-01-01  1.651316  1.394037  0.677368 -2.095631
2013-01-02  0.332189 -1.783594  0.197084  1.122312
2013-01-03  0.141116  0.081434 -2.429343  1.826690
2013-01-04  1.112918  0.225255 -0.665900  0.446125

In [79]:
df1.dropna(axis=0)

                   A         B         C         D    E
2013-01-01  1.651316  1.394037  0.677368 -2.095631  1.0
2013-01-02  0.332189 -1.783594  0.197084  1.122312  1.0

Filling missing data.

In [80]:
df1.fillna(value=5) # np.nan, None, NULL, null

                   A         B         C         D    E
2013-01-01  1.651316  1.394037  0.677368 -2.095631  1.0
2013-01-02  0.332189 -1.783594  0.197084  1.122312  1.0
2013-01-03  0.141116  0.081434 -2.429343  1.826690  5.0
2013-01-04  1.112918  0.225255 -0.665900  0.446125  5.0

To get the boolean mask where values are `nan`

In [81]:
pd.isna(df)

                A      B      C      D
2013-01-01  False  False  False  False
2013-01-02  False  False  False  False
2013-01-03  False  False  False  False
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

## Operations

Operations in general exclude missing data.
Performing a descriptive statistic:

In [82]:
df.mean()

A    0.405666
B   -0.070062
C   -0.244742
D    0.068355
dtype: float64

Same operation on the other axis:

In [83]:
df.mean(1)

2013-01-01    0.406773
2013-01-02   -0.033002
2013-01-03   -0.095026
2013-01-04    0.279600
2013-01-05    0.213394
2013-01-06   -0.532914
Freq: D, dtype: float64

Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically
broadcasts along the specified dimension

In [84]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index = dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [85]:
df.sub(s, axis='index')

                   A         B         C         D
2013-01-01       NaN       NaN       NaN       NaN
2013-01-02       NaN       NaN       NaN       NaN
2013-01-03 -0.858884 -0.918566 -3.429343  0.826690
2013-01-04 -1.887082 -2.774745 -3.665900 -2.553875
2013-01-05 -4.995961 -3.826208 -4.911974 -5.412279
2013-01-06       NaN       NaN       NaN       NaN

## Merge

pandas provide various faciliteis for easily combining together Series and DataFrame objects with various kinds of set logic for the indees and relational algebra functionality in the case of join/ merge-type operations.

Concatenating pandas objects together with concat()

In [86]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0 -0.952473 -0.176114  0.105849  0.441700
1  0.940311 -0.559761 -0.420457  1.036047
2  0.010353 -1.597483 -0.429283 -0.584272
3 -0.200966  1.321759  0.840747  0.341545
4  1.237682 -0.368204 -1.631268  0.655043
5  0.615257 -0.346621  1.458221  0.254142
6 -0.134631 -1.513713 -0.570027 -0.499223
7 -0.177532 -0.343195  0.182625 -0.771229
8 -0.501181 -0.320776 -0.695383 -0.181525
9  0.960032 -0.671025 -0.373150  0.116324

In [87]:
# break it onto pieces
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0 -0.952473 -0.176114  0.105849  0.441700
1  0.940311 -0.559761 -0.420457  1.036047
2  0.010353 -1.597483 -0.429283 -0.584272
3 -0.200966  1.321759  0.840747  0.341545
4  1.237682 -0.368204 -1.631268  0.655043
5  0.615257 -0.346621  1.458221  0.254142
6 -0.134631 -1.513713 -0.570027 -0.499223
7 -0.177532 -0.343195  0.182625 -0.771229
8 -0.501181 -0.320776 -0.695383 -0.181525
9  0.960032 -0.671025 -0.373150  0.116324

Adding a column to a `DataFrame` is relatively fast. However adding a row requires a copy, and may be expensive. It is recorecommended passing a pre-build list of records to the `DataFrame` constructor instead of buildinga `DataFrame` by iteratively appending records to it.

### Join
SQL style merges

In [88]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval' : [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

left

   key  lval
0  foo     1
1  foo     2

In [89]:
right

   key  rval
0  foo     4
1  foo     5

In [90]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

## Grouping

By 'group by' we are referring to a process invloving one or more of the following steps:


*   **Splitting** the data into group base on some criteria
*   **Applying** a function to each group independently

*   **Combining** the results into a data structure

In [91]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                         'foo', 'bar', 'foo', 'bar'],
                   'B': ['one', 'one', 'two', 'three',
                         'two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})
df

     A      B         C         D
0  foo    one -0.379267  1.691932
1  bar    one -0.485102  0.926192
2  foo    two -0.927141  0.592207
3  bar  three  1.383836  0.919753
4  foo    two  0.657760  2.765756
5  bar    two -0.086411 -1.179021
6  foo    one  0.632454 -0.624367
7  bar  three -1.241254 -0.851675

Grouping and then applying the `sum()` funcion to the resuling group

In [92]:
df.groupby('A').sum()

                    B         C         D
A
bar  onethreetwothree -0.428931 -0.184752
foo      onetwotwoone -0.016193  4.425529

Grouping by multiple columns forms a hierarchical index, and again we can apply the sum() function

In [93]:
dir(df)

['A',
 'B',
 'C',
 'D',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [95]:
df.groupby(['A', 'B']).sum()

                  C         D
A   B
bar one   -0.485102  0.926192
    three  0.142582  0.068077
    two   -0.086411 -1.179021
foo one    0.253187  1.067566
    two   -0.269381  3.357964